### ISSUE TITLE
Missing touch.inc

### ISSUE THREAD

**Issue by davidgriffo** [softvelocity/clariontouch#2]
I have tired to compile but it will not as it can not find touch.inc
The reference is in \TouchX\touch.clw

**Comment by rzsv** [comment]
David, it should be all fixed up now.  When that demo was originally written the touch related files were named touch.\* and when we officially shipped them, they were renamed to cwtouch.\* (found in libsrc\win).  There were also a few variables that were renamed.  Get the latest and you should be all set

**Comment by davidgriffo** [comment]
all good. Thanks
